# Generated by Django 3.1.2 on 2023-06-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releations',
            old_name='student',
            new_name='students',
        ),
    ]
